### ISSUE TITLE
Load data from the server

### ISSUE THREAD

**Issue by clementprdhomme** [Vizzuality/surface-water#2]
Hi Dan!

Ok so I'm watching at what you did in _feature/time-series_ and I'm having troubles with the request line 196 (the one which gets the series).

First, there's a CORS issue:

> XMLHttpRequest cannot load http://vizz.water-test.appspot.com/water/series?coords=[...] No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 500.

Then, when directly making a GET request to the URL, I often have a 500 error:

> Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds.

Could you take a look at that when you have free time?

Thanks!

**Comment by d4weed** [comment]
Hey @clementprdhomme you forgot to assign this to dan :) just did

**Comment by danhammer** [comment]
I am at a loss for the CORS issue.  Here are the headers.  This may be a problem with the actual request, such that nothing from the app gets returned (including the headers that I set).  Can you post the headers on the response from [this request](http://vizz.water-test.appspot.com/water/series?coords=[[-119.794921875,39.36297059491874],[-119.86633300781249,39.29179704377487],[-119.8443603515625,39.193948213963644],[-119.70703125,39.198205348894795],[-119.73861694335938,39.32686172585973],[-119.794921875,39.36297059491874]]&begin=2010-01-01&end=2010-12-30) from your machine?  This is what I get:

```
HTTP/1.1 200 OK
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Content-Type: application/json
Content-Encoding: gzip
Vary: Accept-Encoding
Date: Thu, 21 May 2015 13:10:30 GMT
Server: Google Frontend
Content-Length: 712
Alternate-Protocol: 80:quic,p=0
```

The other issue is a bandwidth problem that we won't be able to get around in the short-run.  These requests parse **a lot** of data.  There are limits to the size of the bounding box allowed.  I am not sure what those limits are, but I can start to find out -- so that we can only allow the time series for bounding boxes of a certain (small) size.  

I'm around!  I'm sorry that I don't have immediate answers.

**Comment by d4weed** [comment]
Yep, I confirm I see the header. @clementprdhomme maybe you weren't getting the correct headers because you were actually getting a 500 error. Can you try re-connecting to the endpoint and test it at high zoom levels with small polygons?

**Comment by danhammer** [comment]
I can also work on the error response, so that it's not so cryptic.  I should do this anyway, so that we know if it's an Earth Engine or App Engine server error.  No matter what, it is always a **Google error**.

**Comment by clementprdhomme** [comment]
Hey @d4weed and @danhammer,
So I actually tried as David said (with high zoom level and on a small portion of the screen) and I could get the data. Also there's no more CORS issues.
We could put back the line I commented on the code to retrieve the real chart if you want, but for most of the cases, we'll end up with a 500 error if we don't select a small portion of the map.

**Comment by danhammer** [comment]
So, even if we don't get a 500 error, it still takes a long time to load -- about 20 seconds for a reasonable request.  We would need some additional spinner or loader thing to indicate that the data are coming.
