### ISSUE TITLE
Icon move

### ISSUE THREAD

**Issue by danhammer** [Vizzuality/surface-water#6]
Can you move the logo at the top of the screen to the bottom right to keep the viewport simple and clean?  Sorry for the design ask.  It would be a separate element -- separate from the two `div`'s that constitute the rows at the bottom, which scale everything within those `div`s (specifically the time series).

<img width="1028" alt="screen shot 2016-06-08 at 11 12 52 am" src="https://cloud.githubusercontent.com/assets/428641/15899672/88acd69c-2d6a-11e6-9fc5-c06dec634675.png">

**Comment by clementprdhomme** [comment]
Hi Dan,

I'm afraid I don't know of this could be done because the graph needs some space, especially on smaller screens (think about a small laptop for example).

![The current app on a smaller screen](https://cloud.githubusercontent.com/assets/6073968/15902302/82653f26-2da7-11e6-83f0-b3cdee7ee8a3.png)

As you can see, if we add the logo to the "dashboard" we would have a tiny graph.

**Comment by danhammer** [comment]
Thanks.  This makes sense.  I trust your judgement.  At some point -- later -- for the next iteration, maybe we can revisit the placement so that the logo is less disruptive.
